### PR TITLE
hdspmixer: Hardware output loopback toggle buttons

### PR DESCRIPTION
**Pull request by pfandl**
Hi, as promised in the [sound/pci/rme9652 patch](https://github.com/tiwai/sound/commit/da2a040ee7cfe1dd57d5bec7906cb979c5787a86) here are the user land changes which provide the user the ability to toggle the hardware output loopback functionality per output channel. I tried to hide the buttons for devices which do not expose the snd controls yet, but due to probably unnecessary struggle i cancelled that. Please let me know though should you want them removed for not yet enabled devices.

### CODE REVIEW

**Comment by perexg** [comment]
What was the reason to close this PR? I see you sent the patch to ML, but we can merge the patches from github, too.

**Comment by pfandl** [comment]
Hi, I was asked to send it to ML and since this is a little different than the ones I sent on the ML i closed this.
Patch no. 1 isn't here considered at all and the save/load routines are different. You can ignore this PR please.

**Comment by perexg** [comment]
I don't see the ML request in your conversation with @tiwai . 

Link: https://lore.kernel.org/alsa-devel/2e9bb0b8-ee14-9dc9-1bd8-ecffca3982ac@gmail.com/

I'll close this when merged.

**Comment by pfandl** [comment]
I asked him directly via email since I wasn't sure if this PR got noticed because the reaction time on the ML was so fast.

**Comment by pfandl** [comment]
Hi @perexg the patch was merged, I'll close this if I may. Thanks

**Pull request closed without merging**
